### 메뉴 옵션 그룹 등록
POST http://localhost:8080/stores/28/menu-option-groups
Content-Type: application/json
Set-Cookie: SESSION=N2JhM2ZjNmMtYjYwOS00Zjk2LWE5ZGMtZDg4MDM2NTM5ODg0; Path=/; HttpOnly; SameSite=Lax

{
  "menuId": 97,
  "optionGroupIds": [31]
}

